import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :unread_herring, UnreadHerringWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# No force_ssl here: this app serves plain HTTP on the loopback
# interface only; there is no HTTPS listener to redirect to.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
